apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "tech-docs-test"
  description: "tech-docs-test description"
  annotations:
    github.com/project-slug: JustinDSNTest/tech-docs-test
    backstage.io/techdocs-ref: url:https://github.com/JustinDSNTest/tech-docs-test
spec:
  type: documentation
  lifecycle: experimental
  owner: "JustinDSN"
